### ISSUE TITLE
Mods combined?

### ISSUE THREAD

**Issue by EC-O-DE** [Katalyst6/CSL.TransitAddonMod#2]
Are Traffic++ and Network Extensions going to be merged into single mod?

If so, please give us plenty of options to turn stuff on and off :)

**Comment by originalfoo** [comment]
Will post details on what's happening shortly.

**Comment by originalfoo** [comment]
https://www.reddit.com/r/CitiesSkylinesModding/comments/3p8g8q/rumor_traffic_and_network_extensions_are_perhaps/cw4m14y
